steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['install']

  # Build the Next.js application with environment variables
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['build']
    env:
      - 'NODE_ENV=production'
    secretEnv: 
      - 'SPOTIFY_CLIENT_ID'
      - 'SPOTIFY_CLIENT_SECRET'
      - 'OPENROUTER_KEY'
      - 'SPOTIFY_REDIRECT_URI'

  # Optional: Run tests (if you have any)
  # - name: 'node:20'
  #   entrypoint: 'yarn'
  #   args: ['test']

  # Deploy to Google Cloud Storage or other service
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', '-r', './out/*', 'gs://your-bucket-name/']

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout
timeout: '1200s'
