steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['install']

  # Build the Next.js application with environment variables from Secret Manager
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['build']
    env:
      - 'NODE_ENV=production'
    secretEnv: 
      - 'SPOTIFY_CLIENT_ID'
      - 'SPOTIFY_CLIENT_SECRET'
      - 'OPENROUTER_KEY'
      - 'SPOTIFY_REDIRECT_URI'

  # Optional: Run tests (if you have any)
  # - name: 'node:20'
  #   entrypoint: 'yarn'
  #   args: ['test']

  # Deploy to Google Cloud Storage or other service
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', '-r', './out/*', 'gs://your-bucket-name/']

# Configure secrets from Google Secret Manager
availableSecrets:
  secretManager:
    - versionName: 'projects/spotify-shop-central/secrets/SPOTIFY_CLIENT_ID/versions/latest'
      env: 'SPOTIFY_CLIENT_ID'
    - versionName: 'projects/spotify-shop-central/secrets/SPOTIFY_CLIENT_SECRET/versions/latest'
      env: 'SPOTIFY_CLIENT_SECRET'
    - versionName: 'projects/spotify-shop-central/secrets/OPENROUTER_KEY/versions/latest'
      env: 'OPENROUTER_KEY'
    - versionName: 'projects/spotify-shop-central/secrets/SPOTIFY_REDIRECT_URI/versions/latest'
      env: 'SPOTIFY_REDIRECT_URI'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'

# Build timeout
timeout: '1200s'
