steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['install', '--frozen-lockfile']

  # Build the application
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['build']

  # Deploy to Firebase
  # Note: The Cloud Build Service Account must have the 'Firebase Admin' role.
  - name: 'node:20'
    entrypoint: 'yarn'
    args: ['firebase', 'deploy', '--project', 'spotify-shop-central']
